### PR TITLE
gracefully handle db failures on startup

### LINKED ISSUE #55: Gracefully handle DB connection failures on startup
## Description
Instead of just crashing the server on startup if database fails to connect, the app should be running and retry the database connection and then panicking

### PR DESCRIPTION
**Pull request by archiik04**
Fixes #55 

## Problem
Server was crashing immediately on startup if the database failed to connect, due to log.Fatal() being called on the first failed ping.

## Changes

Database Layer (db.go)
- Background Health Monitoring: Added goroutine that pings DB every 10 seconds and updates atomic health flag.
- Connect() now attempt 5 retries with exponential backoff instead of direct log.fatal() on ping failure. Updated fixed backoff to exponential backoff.
- Health check api endpoint: this is to check isDBHealthy() function for runtime avalaible checks.

Middleware (auth.go)
- Pre-Auth Check: Added DB health verification before JWT parsing
- Graceful Failure: Returns 503 "authentication service unavailable" when DB is down, blocking auth operations safely

Routes (route.go)
- Health endpoint: /health to return 
- 503 {"status":"degraded","db":"down"} when DB unavailable
- 200 {"status":"ok","db":"up"} when DB healthy

## Testing

1) Start the server when the DB is down:

image

2) Check health with db down

image

3) Start the DB while the server is running

image

4) Stop DB while the server is running

image

5) Test Auth Request with DB Down

image

6) Restart server with db up

image

### CODE REVIEW

File: backend/internal/routes/routes.go [hunk 1]
```diff
@@ -12,7 +13,11 @@ func SetupRoutes(router *gin.Engine, authHandler *handlers.AuthHandler, todoHand
 	router.Use(middleware.ErrorHandler())
 
 	router.GET("/health", func(c *gin.Context) {
-		c.JSON(200, gin.H{"status": "ok"})
+		if !database.IsDBHealthy() {
```
Comment (TanishqSingla) [inline backend/internal/routes/routes.go]: Application should only show it's own health, not the db connection health.

Since healthcheck routes are constantly polled, at a short interval, this will create unecessary calls to db

**Review by TanishqSingla — CHANGES_REQUESTED** [review]

File: backend/internal/routes/routes.go (hunk 1 above)
Comment (archiik04) [reply backend/internal/routes/routes.go]: Got it! will update it.

File: backend/internal/database/db.go [hunk 2]
```diff
@@ -26,15 +37,62 @@ func Connect() {
...
+			delay *= 2
+			if delay > dbStartupMaxDelay {
+				delay = dbStartupMaxDelay
+			}
+		}
+	}
+	return fmt.Errorf("database unreachable after %d attempts", dbMaxStartupAttempts)
+}
+
+func monitorDatabase() {
```
Comment (TanishqSingla) [inline backend/internal/database/db.go]: We should not ping database at regular interval, this doesn't solve our issue. 
It's same as the healthcheck route issue

File: backend/internal/middleware/auth.go [hunk 3]
```diff
@@ -21,10 +22,19 @@ func AuthRequired() gin.HandlerFunc {
 		// Accept standard Authorization header format without forcing clients to preprocess it.
 		tokenStr = strings.TrimPrefix(tokenStr, "Bearer ")
 
+		if !database.IsDBHealthy() {
```
Comment (TanishqSingla) [inline backend/internal/middleware/auth.go]: This is okay, but it won't be feasible to add such checks at ever request or middleware that relies on database. 
Find what we can do better

**Review by TanishqSingla — CHANGES_REQUESTED** [review]
For now let's focus on database connection on application startup, will handle the connection on requests later

File: backend/internal/middleware/auth.go (hunk 3 above)
Comment (archiik04) [reply backend/internal/middleware/auth.go]: Removed it for now. Will search for what else we can do.

File: backend/internal/database/db.go (hunk 2 above)
Comment (archiik04) [reply backend/internal/database/db.go]: Yes, removed this function entirely since it is not needed to ping the database at each interval to monitor it.

**Review by TanishqSingla — APPROVED** [review]
